### PR TITLE
Jackson module

### PR DESCRIPTION
**Pull request by XakepSDK**
Add support for jackson

### CODE REVIEW

**Comment by XakepSDK** [comment]
Tests were taken from GSON version.
Known itches: uses static access to mapper to convert object to node, will be fixed after this resolved: https://github.com/FasterXML/jackson-databind/issues/2411
It's not a problem, but it would be better if i could avoid this access.

Known issues:
I'm doing this:
```
private static final Version VERSION = VersionUtil.parseVersion("3.0.2", "net.kyori", "text-serializer-jackson");
```
How can i hardcoded values to values from gradle?

**Comment by XakepSDK** [comment]
Bump

**Comment by liach** [comment]
Consider formatting your code with code style/inspections from https://github.com/kashike/dotfiles.intellij

**Comment by XakepSDK** [comment]
Fixed

**Comment by XakepSDK** [comment]
Do i need make more changes?

**Comment by kashike** [comment]
Could you please rebase against `master`?

**Comment by XakepSDK** [comment]
I think i did it. Should i squash this mess?

**Comment by XakepSDK** [comment]
Well, this git history looks so sick. Let me re-do PR.

**Comment by mikroskeem** [comment]
Could've just used the force, Luke ;) `git push --force`

**Pull request closed without merging**
